CC = gcc
DEBUG = -g

all :
	gcc -g main.c Threshold.c Incidents.c DatabaseRecord.c DateAndTime.c DisabledIncidents.c EmailInfo.c StationPair.c StringAndFileMethods.c TypeOfIncident.c -o Automated_CSS_Alarm_Tool
